### ISSUE TITLE
Toggle turning off after clicking play

### ISSUE THREAD

**Issue by guidodelphora** [Sammmte/unity-toolbar-extender-ui-toolkit#1]
Hello !

I'm not sure which is the expected behaviour, I couldn't find it in the documentation. But I have a toggle that I want to be able to turn it on and off, it's already working but if I click it and make it true, when I click Play, it goes to false. And if I quit play the toggle is off.

Unity 2022.3.22.f1
Package Version: 1.0.1

Thanks! :)

**Comment by Sammmte** [comment]
Hi friend! thank you for opening an issue. This is expected behavior, because Unity reloads its domain when enters play mode. i.e. all things in memory (like a boolean stored in a variable) are destroyed. You need to store this value somewhere. Currently i'm working on a feature to provide support for these case scenarios. Will be releasing it soon.

So far, the best way I know is using EditorPrefs to store your value. Like this:

`
[MainToolbarElement("MyToggle")]
public class MyToggle : Toggle
{
    private const string VALUE_SAVE_KEY = "ToggleValue";

    private bool TheValue
    {
        get => EditorPrefs.GetBool(VALUE_SAVE_KEY);
        set => EditorPrefs.SetBool(VALUE_SAVE_KEY, value);
    }

    public MyToggle() : base("My Toggle")
    {
        value = TheValue;

        RegisterCallback<ChangeEvent<bool>>(OnValueChanged);
    }

    private void OnValueChanged(ChangeEvent<bool> changeEvent)
    {
        TheValue = changeEvent.newValue;
    }
}
`

Please let me know if this helps!

**Comment by guidodelphora** [comment]
Hello cool developer! 
Thanks for the quick response, and sorry for my super late response.
So yep, this solution work perfectly :) 

Thanks a lot!
